### ISSUE TITLE
Pass through html tags

### ISSUE THREAD

**Issue by bterlson** [rbuckton/grammarkdown#20]
It would be nice to be able to use \<ins> and \<del> tags, especially. See also bterlson/ecmarkup#95.

**Comment by rbuckton** [comment]
I've been looking into this and the main issue is that currently the scanner/parser uses `<` and `>` to indicate a unicode character, such as `<CR>`, `<LF>`, etc. (see https://github.com/rbuckton/grammarkdown/blob/master/spec/es6.grammar#L40).

I have a few options here:

1. only treat `<`..`>` as a character token if the characters are all-caps, allowing `<ins>` and `<del>` to work, along with other HTML.
2. special case `<ins>` and `<del>` tags (and their end tags).

I think option 1 is probably fine, and is the approach I'm looking into.

**Comment by bterlson** [comment]
Agree option 1 is probably best.

**Comment by rbuckton** [comment]
Fixed in 0456140

**Comment by rbuckton** [comment]
@bterlson Let me know if the solution in version 1.0.4 works for your scenario.

**Comment by domenic** [comment]
I've updated to grammarkdown 1.0.4 and my cancelable promise spec is still not passing things through, hmm: https://github.com/domenic/cancelable-promise/blob/2f601acb3d4d438be0ebc9e4e54e6febde9d7a3a/spec.html#L1211

**Comment by rbuckton** [comment]
@domenic I'll take another look, but I'll be on vacation for the next week and may not be able to address this until I return.

Speaking of promise cancellation, have you seen https://github.com/rbuckton/prex, specifically https://github.com/rbuckton/prex/blob/master/docs/cancellation.md with respect to cancellation tokens?

**Comment by rbuckton** [comment]
@domenic You may need to wait on ecmarkup. it looks like the <ins>/<del> elements are not passed to `gmdCompile` in ecmarkup, so they're not making it to grammarkdown.

**Comment by bterlson** [comment]
@rbuckton I was hoping to find you at the design meeting. I am also having the same problem - no parse errors, but the tags simply disappear from the output. Is it possible the emu emitter hasn't been updated? It's also possible it's something in Emu. I was hoping to check today.

**Comment by bterlson** [comment]
oh I see you replied - I think that says \<ins>/\<del> tags aren't being passed. Will investigate this now.

**Comment by rbuckton** [comment]
@bterlson Sorry, I'm OOF today and out until 8/1 on vacation :). The issue is on line 12 in Grammar.js in ecmarkup, you pass `node.textContent` to `gmdCompile`.
